"""Endpoint cases for the blockchain domain (42 operations)."""

from __future__ import annotations

from typing import List

from cryptures import types as t

from ._case import Case

D = "/api/v1/blockchain/data"

BLOCKCHAIN_CASES: List[Case] = [
    # ======================================================== blockchain.data
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("ETH", "0xabc"),
        "GET",
        f"{D}/balance/ETH/0xabc",
        response={"balance": "0.1234"},
        check=lambda r: isinstance(r, t.BalanceSimple) and r.balance == "0.1234",
        variant="simple",
    ),
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("BTC", "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"),
        "GET",
        f"{D}/balance/BTC/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
        response={
            "balance": "5000",
            "incoming": "7000",
            "outgoing": "2000",
            "incomingPending": "0",
            "outgoingPending": "0",
        },
        check=lambda r: isinstance(r, t.BalanceUtxo) and r.incoming == "7000",
        variant="utxo",
    ),
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("CELO", "0xc"),
        "GET",
        f"{D}/balance/CELO/0xc",
        response={"celo": "1", "cUsd": "2", "cEur": "3"},
        check=lambda r: isinstance(r, t.BalanceCelo) and r.cEur == "3",
        variant="celo",
    ),
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("ADA", "addr1"),
        "GET",
        f"{D}/balance/ADA/addr1",
        response=[{"currency": {"symbol": "ADA", "decimals": 6}, "value": "12.5"}],
        check=lambda r: (
            isinstance(r, list) and isinstance(r[0], t.CardanoAsset) and r[0].currency.decimals == 6
        ),
        variant="cardano",
    ),
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("XLM", "GABC"),
        "GET",
        f"{D}/balance/XLM/GABC",
        response={
            "account_id": "GABC",
            "sequence": "1",
            "balances": [{"asset_type": "native", "balance": "9"}],
        },
        check=lambda r: isinstance(r, t.BalanceStellar) and r.balances[0].asset_type == "native",
        variant="stellar",
    ),
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("XRP", "rXYZ"),
        "GET",
        f"{D}/balance/XRP/rXYZ",
        response={"balance": "1000000", "assets": [{"balance": "5", "currency": "USD"}]},
        check=lambda r: isinstance(r, t.BalanceXrp) and r.assets[0].currency == "USD",
        variant="xrp",
    ),
    Case(
        "balance.check",
        "blockchain.data.get_balance",
        lambda c: c.blockchain.data.get_balance("TRON", "TXYZ"),
        "GET",
        f"{D}/balance/TRON/TXYZ",
        response={"address": "TXYZ", "balance": 1000000, "trc10": [], "trc20": [{"T": "1"}], "bandwidth": {}},
        check=lambda r: isinstance(r, t.BalanceTron) and r.balance == 1000000 and isinstance(r.balance, int),
        variant="tron",
    ),
    Case(
        "balance.batch",
        "blockchain.data.get_balances_batch",
        lambda c: c.blockchain.data.get_balances_batch(
            "ethereum-mainnet", ["0xabc", "0xdef"], unix=1758700000
        ),
        "POST",
        f"{D}/balance/batch",
        json={"chain": "ethereum-mainnet", "addresses": "0xabc,0xdef", "unix": 1758700000},
        response={
            "result": [
                {
                    "chain": "ethereum-mainnet",
                    "address": "0xabc",
                    "balance": "1.5",
                    "lastUpdatedBlockNumber": 21000000,
                    "type": "native",
                }
            ],
            "prevPage": "",
            "nextPage": "",
        },
        check=lambda r: (
            isinstance(r, t.BalanceBatchResponse) and r.result[0].lastUpdatedBlockNumber == 21000000
        ),
    ),
    Case(
        "token.transfers",
        "blockchain.data.get_token_transfers",
        lambda c: c.blockchain.data.get_token_transfers(
            "TRON",
            "TXYZ",
            next="cur",
            only_confirmed=True,
            only_unconfirmed=False,
            only_to=True,
            only_from=False,
            order_by="desc",
            min_timestamp=1,
            max_timestamp=2,
            contract_address="TR7",
        ),
        "GET",
        f"{D}/token-transfers/TRON/TXYZ",
        query={
            "next": "cur",
            "onlyConfirmed": "true",
            "onlyUnconfirmed": "false",
            "onlyTo": "true",
            "onlyFrom": "false",
            "orderBy": "desc",
            "minTimestamp": "1",
            "maxTimestamp": "2",
            "contractAddress": "TR7",
        },
        response={
            "transactions": [
                {
                    "txID": "8ea0",
                    "tokenInfo": {"symbol": "USDT", "address": "TR7", "decimals": 6, "name": "Tether USD"},
                    "from": "TVgY",
                    "to": "TXYZ",
                    "type": "Transfer",
                    "value": "1994194",
                }
            ]
        },
        check=lambda r: isinstance(r, t.TokenTransfersResponse) and r.transactions[0].from_ == "TVgY",
    ),
    Case(
        "tx.history",
        "blockchain.data.get_transaction_history",
        lambda c: c.blockchain.data.get_transaction_history("BNB", "0xdef", page_size=50, offset=0),
        "GET",
        f"{D}/history/BNB/0xdef",
        query={"pageSize": "50", "offset": "0"},
        response={
            "result": [
                {
                    "chain": "bsc-mainnet",
                    "hash": "0x5494",
                    "address": "0xdef",
                    "counterAddress": "0x0d4a",
                    "blockNumber": 16819465,
                    "transactionType": "fungible",
                    "transactionSubtype": "incoming",
                    "amount": "0.99",
                    "timestamp": 1678715303000,
                }
            ],
            "prevPage": "",
            "nextPage": "",
        },
        check=lambda r: (
            isinstance(r, t.TransactionHistoryUnified) and r.result[0].transactionSubtype == "incoming"
        ),
        variant="unified",
    ),
    Case(
        "tx.history",
        "blockchain.data.get_transaction_history",
        lambda c: c.blockchain.data.get_transaction_history("BTC", "bc1q"),
        "GET",
        f"{D}/history/BTC/bc1q",
        response=[{"hash": "abc", "inputs": [], "outputs": []}],
        check=lambda r: isinstance(r, list) and r[0]["hash"] == "abc",
        variant="chain-native",
    ),
    Case(
        "tx.history",
        "blockchain.data.get_transaction_history",
        lambda c: c.blockchain.data.get_transaction_history("TRON", "TXYZ"),
        "GET",
        f"{D}/history/TRON/TXYZ",
        response={"transactions": [{"txID": "1"}], "next": "n1"},
        check=lambda r: isinstance(r, t.TransactionHistoryTron) and r.next == "n1",
        variant="tron",
    ),
    Case(
        "portfolio.get",
        "blockchain.data.get_portfolio",
        lambda c: c.blockchain.data.get_portfolio(
            "ETH",
            "0xae68",
            token_types=["native", "fungible"],
            exclude_metadata=False,
            page_size=50,
            offset=0,
        ),
        "GET",
        f"{D}/portfolio/ETH/0xae68",
        query={"tokenTypes": "native,fungible", "excludeMetadata": "false", "pageSize": "50", "offset": "0"},
        response={
            "result": [
                {
                    "chain": "ethereum-mainnet",
                    "address": "0xae68",
                    "balance": "2.88",
                    "denominatedBalance": "2880000000000000000",
                    "decimals": 18,
                    "type": "native",
                }
            ],
            "prevPage": "",
            "nextPage": "",
        },
        check=lambda r: isinstance(r, t.PortfolioResponse) and r.result[0].decimals == 18,
    ),
    Case(
        "balance-history.get",
        "blockchain.data.get_balance_history",
        lambda c: c.blockchain.data.get_balance_history("BTC", "1A1z", time="2026-01-01T00:00:00Z"),
        "GET",
        f"{D}/balance-history/BTC/1A1z",
        query={"time": "2026-01-01T00:00:00Z"},
        response={
            "result": [
                {
                    "chain": "bitcoin-mainnet",
                    "address": "1A1z",
                    "balance": "0.5",
                    "denominatedBalance": "50000000",
                    "decimals": 8,
                    "type": "native",
                }
            ],
            "prevPage": "",
            "nextPage": "",
        },
        check=lambda r: isinstance(r, t.BalanceHistoryResponse) and r.result[0].balance == "0.5",
    ),
    Case(
        "security.address-check",
        "blockchain.data.check_address_security",
        lambda c: c.blockchain.data.check_address_security("0x002bf459dc58584d58886169ea0e80f3ca95ffaf"),
        "GET",
        f"{D}/security/0x002bf459dc58584d58886169ea0e80f3ca95ffaf",
        response={
            "status": "invalid",
            "address": "0x002bf459dc58584d58886169ea0e80f3ca95ffaf",
            "source": "CryptoScamDB",
            "description": "Trust trading scam site",
        },
        check=lambda r: isinstance(r, t.AddressSecurityCheck) and r.status == "invalid",
    ),
    Case(
        "exchange.rate",
        "blockchain.data.get_exchange_rate",
        lambda c: c.blockchain.data.get_exchange_rate("BTC", base_pair="USD"),
        "GET",
        f"{D}/rate/BTC",
        query={"basePair": "USD"},
        response={"value": "63000.00", "basePair": "USD", "id": "BTC", "timestamp": 1759481315000},
        check=lambda r: (
            isinstance(r, t.ExchangeRate) and r.value == "63000.00" and r.timestamp == 1759481315000
        ),
    ),
    Case(
        "exchange.rate.contract",
        "blockchain.data.get_exchange_rate_by_contract",
        lambda c: c.blockchain.data.get_exchange_rate_by_contract(
            chain="ethereum-mainnet", contract_address="0xdac1", base_pair="USD"
        ),
        "GET",
        f"{D}/rate/contract",
        query={"chain": "ethereum-mainnet", "contractAddress": "0xdac1", "basePair": "USD"},
        response={
            "value": "0.85",
            "basePair": "USD",
            "timestamp": 1759481315000,
            "chain": "ethereum-mainnet",
            "address": "0xdac1",
        },
        check=lambda r: isinstance(r, t.ContractExchangeRate) and r.address == "0xdac1",
    ),
    Case(
        "exchange.rate.batch",
        "blockchain.data.get_exchange_rates_batch",
        lambda c: c.blockchain.data.get_exchange_rates_batch(
            [
                t.ExchangeRateRequest(batchId="1", symbol="BTC", basePair="USD"),
                {"batchId": "2", "symbol": "ETH"},
            ]
        ),
        "POST",
        f"{D}/rate/batch",
        json=[{"batchId": "1", "symbol": "BTC", "basePair": "USD"}, {"batchId": "2", "symbol": "ETH"}],
        response=[{"batchId": "1", "symbol": "BTC", "value": "63000", "basePair": "USD", "timestamp": 1}],
        check=lambda r: isinstance(r[0], t.ExchangeRateBatchItem) and r[0].batchId == "1",
    ),
    Case(
        "sentiment.fear-greed",
        "blockchain.data.get_fear_greed_index",
        lambda c: c.blockchain.data.get_fear_greed_index(limit=1, date_format="world"),
        "GET",
        f"{D}/sentiment/fear-greed",
        query={"limit": "1", "date_format": "world"},
        response={
            "name": "Fear and Greed Index",
            "data": [
                {
                    "value": "63",
                    "value_classification": "Greed",
                    "timestamp": "1788307200",
                    "time_until_update": "29641",
                }
            ],
            "metadata": {"error": None},
        },
        check=lambda r: isinstance(r, t.FearGreedIndex) and r.data[0].value_classification == "Greed",
    ),
    Case(
        "market.global",
        "blockchain.data.get_market_global",
        lambda c: c.blockchain.data.get_market_global(),
        "GET",
        f"{D}/market/global",
        response=[
            {
                "coins_count": 14993,
                "active_markets": 28840,
                "total_mcap": 2589177854944.6934,
                "btc_d": "59.50",
            }
        ],
        check=lambda r: isinstance(r[0], t.MarketGlobalStats) and r[0].coins_count == 14993,
    ),
    Case(
        "market.assets",
        "blockchain.data.list_market_assets",
        lambda c: c.blockchain.data.list_market_assets(),
        "GET",
        f"{D}/market/assets",
        response={"data": [{"id": "90", "symbol": "BTC", "name": "Bitcoin", "nameid": "bitcoin", "rank": 1}]},
        check=lambda r: isinstance(r, t.MarketAssetList) and r.data[0].rank == 1,
    ),
    Case(
        "market.tickers",
        "blockchain.data.list_market_tickers",
        lambda c: c.blockchain.data.list_market_tickers(start=0, limit=50),
        "GET",
        f"{D}/market/tickers",
        query={"start": "0", "limit": "50"},
        response={
            "data": [{"id": "90", "symbol": "BTC", "price_usd": "77146.66", "volume24": 26551212429.492466}],
            "info": {"coins_num": 14993, "time": 1788363842},
        },
        check=lambda r: isinstance(r, t.MarketTickerList) and r.info.coins_num == 14993,
    ),
    Case(
        "market.tickers.single",
        "blockchain.data.get_market_tickers",
        lambda c: c.blockchain.data.get_market_tickers(["90", "80"]),
        "GET",
        f"{D}/market/tickers/90%2C80",
        response=[
            {"id": "90", "symbol": "BTC", "name": "Bitcoin", "price_usd": "64420.92"},
            {"id": "80", "symbol": "ETH", "name": "Ethereum", "price_usd": "1912.50"},
        ],
        check=lambda r: len(r) == 2 and isinstance(r[1], t.MarketTickerSummary) and r[1].symbol == "ETH",
    ),
    Case(
        "market.movers",
        "blockchain.data.get_market_movers",
        lambda c: c.blockchain.data.get_market_movers(sort="24h"),
        "GET",
        f"{D}/market/movers",
        query={"sort": "24h"},
        response={"data": {"winners": [{"id": "1"}], "losers": [{"id": "2"}]}},
        check=lambda r: isinstance(r, t.MarketMovers) and r.data.losers[0]["id"] == "2",
    ),
    Case(
        "market.coin.info",
        "blockchain.data.get_coin_info",
        lambda c: c.blockchain.data.get_coin_info("90"),
        "GET",
        f"{D}/market/coin/90/info",
        response=[{"id": "90", "symbol": "BTC", "ath": 126020.77458949, "startdate": None, "platform": None}],
        check=lambda r: (
            isinstance(r[0], t.CoinInfo) and r[0].ath == 126020.77458949 and r[0].platform is None
        ),
    ),
    Case(
        "market.coin.ohlcv",
        "blockchain.data.get_coin_ohlcv",
        lambda c: c.blockchain.data.get_coin_ohlcv("90"),
        "GET",
        f"{D}/market/coin/90/ohlcv",
        response=[[1367136917, 135.3, 135.98, 132.1, 134.21, 0]],
        check=lambda r: r[0][0] == 1367136917 and r[0][1] == 135.3,
    ),
    Case(
        "market.coin.markets",
        "blockchain.data.get_coin_markets",
        lambda c: c.blockchain.data.get_coin_markets("90"),
        "GET",
        f"{D}/market/coin/90/markets",
        response=[{"name": "Coinone", "base": "BTC", "quote": "KRW", "price": 106110000, "time": 1788363542}],
        check=lambda r: isinstance(r[0], t.CoinMarket) and r[0].quote == "KRW",
    ),
    Case(
        "market.coin.social",
        "blockchain.data.get_coin_social",
        lambda c: c.blockchain.data.get_coin_social("90"),
        "GET",
        f"{D}/market/coin/90/social",
        response={
            "reddit": {"avg_active_users": None, "subscribers": 8124337},
            "twitter": {"followers_count": None, "status_count": None},
        },
        check=lambda r: isinstance(r, t.CoinSocialStats) and r.reddit.subscribers == 8124337,
    ),
    Case(
        "market.exchanges",
        "blockchain.data.list_exchanges",
        lambda c: c.blockchain.data.list_exchanges(),
        "GET",
        f"{D}/market/exchanges",
        response={"5": {"id": "5", "name": "Binance", "name_id": "binance", "active_pairs": 914}},
        check=lambda r: isinstance(r["5"], t.Exchange) and r["5"].name == "Binance",
    ),
    Case(
        "market.exchanges.single",
        "blockchain.data.get_exchange",
        lambda c: c.blockchain.data.get_exchange("5"),
        "GET",
        f"{D}/market/exchanges/5",
        response={
            "0": {"name": "Binance", "date_live": None, "url": "https://www.binance.com"},
            "pairs": [{"base": "BTC", "quote": "USDT", "volume": 1087137239.3136, "price": 77328}],
        },
        check=lambda r: (
            isinstance(r, t.ExchangeDetail) and r.metadata.name == "Binance" and r.pairs[0].price == 77328
        ),
    ),
    # ===================================================== blockchain.lookups
    Case(
        "tx.hash",
        "blockchain.lookups.get_transaction",
        lambda c: c.blockchain.lookups.get_transaction("ETH", "0xd49f"),
        "GET",
        f"{D}/tx/ETH/0xd49f",
        response=[
            {
                "chain": "ethereum-mainnet",
                "hash": "0xd49f",
                "address": "0x4740",
                "counterAddress": "0x9757",
                "blockNumber": 16410533,
                "transactionIndex": 139,
                "transactionType": "native",
                "transactionSubtype": "outgoing",
                "amount": "-3.9e-17",
                "timestamp": 1673765531000,
            }
        ],
        check=lambda r: (
            isinstance(r, list) and isinstance(r[0], t.EvmTransferEntry) and r[0].transactionIndex == 139
        ),
        variant="evm",
    ),
    Case(
        "tx.hash",
        "blockchain.lookups.get_transaction",
        lambda c: c.blockchain.lookups.get_transaction("BTC", "3eb2"),
        "GET",
        f"{D}/tx/BTC/3eb2",
        response={"hash": "3eb2", "blockNumber": 1, "fee": 100, "inputs": [{}], "outputs": [{}, {}]},
        check=lambda r: isinstance(r, t.UtxoTransaction) and len(r.outputs) == 2,
        variant="utxo",
    ),
    Case(
        "tx.hash",
        "blockchain.lookups.get_transaction",
        lambda c: c.blockchain.lookups.get_transaction("TRON", "abcd"),
        "GET",
        f"{D}/tx/TRON/abcd",
        response={"txID": "abcd", "rawData": {"contract": []}, "signature": ["s"]},
        check=lambda r: isinstance(r, t.TronTransaction) and r.signature == ["s"],
        variant="tron",
    ),
    Case(
        "tx.hash",
        "blockchain.lookups.get_transaction",
        lambda c: c.blockchain.lookups.get_transaction("SOL", "5sig"),
        "GET",
        f"{D}/tx/SOL/5sig",
        response={"slot": 123, "meta": {"fee": 5000}},
        check=lambda r: isinstance(r, t.ChainNativeTransaction) and r.model_extra["slot"] == 123,
        variant="chain-native",
    ),
    Case(
        "block.get",
        "blockchain.lookups.get_block",
        lambda c: c.blockchain.lookups.get_block("BTC", 937061),
        "GET",
        f"{D}/block/BTC/937061",
        response={
            "hash": "00000000000000000001b296",
            "height": 937061,
            "mediantime": 1771321646,
            "bits": 386022526,
            "difficulty": 125864590119494.3,
            "chainwork": "01100e85",
            "confirmations": 28978,
            "merkleRoot": "17589be1",
        },
        check=lambda r: isinstance(r, t.UtxoBlock) and r.height == 937061,
        variant="utxo",
    ),
    Case(
        "block.get",
        "blockchain.lookups.get_block",
        lambda c: c.blockchain.lookups.get_block("ETH", "0xblock"),
        "GET",
        f"{D}/block/ETH/0xblock",
        response={
            "hash": "0xblock",
            "number": 100,
            "parentHash": "0xparent",
            "transactions": [{"hash": "0x1"}],
        },
        check=lambda r: isinstance(r, t.EvmBlock) and r.number == 100,
        variant="evm",
    ),
    Case(
        "block.get",
        "blockchain.lookups.get_block",
        lambda c: c.blockchain.lookups.get_block("TRON", "86058853"),
        "GET",
        f"{D}/block/TRON/86058853",
        response={"blockNumber": 86058853, "hash": "0000abc", "witnessAddress": "41ab"},
        check=lambda r: isinstance(r, t.TronBlock) and r.witnessAddress == "41ab",
        variant="tron",
    ),
    Case(
        "block.get",
        "blockchain.lookups.get_block",
        lambda c: c.blockchain.lookups.get_block("XRP", "90000000"),
        "GET",
        f"{D}/block/XRP/90000000",
        response={"ledger_index": 90000000},
        check=lambda r: isinstance(r, t.ChainNativeBlock),
        variant="chain-native",
    ),
    Case(
        "block.latest",
        "blockchain.lookups.get_latest_block",
        lambda c: c.blockchain.lookups.get_latest_block(),
        "GET",
        f"{D}/block/TRON/latest",
        response={
            "blockID": "00000000052131e4",
            "block_header": {
                "raw_data": {
                    "timestamp": 1788856416000,
                    "number": 86058853,
                    "witness_address": "417f",
                    "version": 36,
                },
                "witness_signature": "4d7c",
            },
            "transactions": [],
        },
        check=lambda r: isinstance(r, t.TronLatestBlock) and r.block_header.raw_data.number == 86058853,
    ),
    Case(
        "tokens.get",
        "blockchain.lookups.get_token",
        lambda c: c.blockchain.lookups.get_token("ETH", "0xbc4c", token_id="1"),
        "GET",
        f"{D}/tokens/ETH/0xbc4c",
        query={"tokenId": "1"},
        response={
            "symbol": "ETH",
            "supply": "122373866217800000000000000",
            "decimals": 18,
            "tokenType": "native",
        },
        check=lambda r: isinstance(r, t.TokenMetadata) and r.tokenType == "native",
    ),
    Case(
        "utxo.list",
        "blockchain.lookups.list_utxos",
        lambda c: c.blockchain.lookups.list_utxos("BTC", "34xp", total_value=0.001),
        "GET",
        f"{D}/utxo/BTC/34xp",
        query={"totalValue": "0.001"},
        response=[
            {
                "chain": "bitcoin-mainnet",
                "address": "34xp",
                "txHash": "3eb2",
                "index": 24,
                "value": 0.00012313,
                "valueAsString": "0.00012313",
            }
        ],
        check=lambda r: isinstance(r[0], t.Utxo) and r[0].index == 24,
    ),
    Case(
        "utxo.batch",
        "blockchain.lookups.get_utxos_batch",
        lambda c: c.blockchain.lookups.get_utxos_batch(
            chain="bitcoin-mainnet", addresses=["34xp", "bc1q"], total_value=0.001
        ),
        "POST",
        f"{D}/utxo/batch",
        json={"addresses": ["34xp", "bc1q"], "totalValue": 0.001, "chain": "bitcoin-mainnet"},
        response=[
            {
                "address": "34xp",
                "utxos": [{"txHash": "3eb2", "index": 24, "value": 0.1}],
                "transactionPossible": True,
            },
            {"address": "bc1q", "utxos": [], "transactionPossible": False},
        ],
        check=lambda r: isinstance(r[0], t.AddressUtxos) and r[0].transactionPossible and not r[1].utxos,
    ),
    # ================================================== blockchain.operations
    Case(
        "tx.send",
        "blockchain.operations.send_transaction",
        lambda c: c.blockchain.operations.send_transaction(
            "ETH",
            t.TxSendEvmRequest(
                currency="ETH",
                amount="0.001",
                to="0x5041",
                fee=t.EvmFee(gasLimit="21000", gasPrice="50"),
                nonce=0,
                fromPrivateKey="PK",
            ),
        ),
        "POST",
        "/api/v1/blockchain/operations/transaction/ETH/send",
        json={
            "currency": "ETH",
            "amount": "0.001",
            "to": "0x5041",
            "fee": {"gasLimit": "21000", "gasPrice": "50"},
            "nonce": 0,
            "fromPrivateKey": "PK",
        },
        response={"txId": "0x4a19"},
        check=lambda r: isinstance(r, t.TransactionId) and r.txId == "0x4a19",
        variant="evm",
    ),
    Case(
        "tx.send",
        "blockchain.operations.send_transaction",
        lambda c: c.blockchain.operations.send_transaction(
            "BTC",
            t.TxSendUtxoRequest(
                fromUTXO=[t.UtxoInput(txHash="aa", index=0, privateKey="K")],
                to=[t.UtxoOutput(address="bc1q", value=0.0001)],
                changeAddress="bc1change",
            ),
        ),
        "POST",
        "/api/v1/blockchain/operations/transaction/BTC/send",
        json={
            "fromUTXO": [{"txHash": "aa", "index": 0, "privateKey": "K"}],
            "to": [{"address": "bc1q", "value": 0.0001}],
            "changeAddress": "bc1change",
        },
        response={"txId": "btctx"},
        check=lambda r: r.txId == "btctx",
        variant="utxo",
    ),
    Case(
        "tx.send",
        "blockchain.operations.send_transaction",
        lambda c: c.blockchain.operations.send_transaction(
            "SOL", {"from": "SoLa", "to": "SoLb", "amount": "1", "fromPrivateKey": "PK"}
        ),
        "POST",
        "/api/v1/blockchain/operations/transaction/SOL/send",
        json={"from": "SoLa", "to": "SoLb", "amount": "1", "fromPrivateKey": "PK"},
        response={"txId": "soltx"},
        check=lambda r: r.txId == "soltx",
        variant="dict",
    ),
    Case(
        "rpc.gateway",
        "blockchain.operations.rpc",
        lambda c: c.blockchain.operations.rpc("SOL", "getSignaturesForAddress", ["SoLAddr", {"limit": 10}]),
        "POST",
        "/api/v1/blockchain/operations/rpc/SOL",
        json={
            "jsonrpc": "2.0",
            "method": "getSignaturesForAddress",
            "id": 1,
            "params": ["SoLAddr", {"limit": 10}],
        },
        response={"jsonrpc": "2.0", "id": 1, "result": [{"signature": "sigExample", "slot": 123}]},
        check=lambda r: isinstance(r, t.RpcResponse) and r.error is None and r.result[0]["slot"] == 123,
    ),
    Case(
        "tx.broadcast",
        "blockchain.operations.broadcast",
        lambda c: c.blockchain.operations.broadcast("BTC", "62BD544D"),
        "POST",
        "/api/v1/blockchain/operations/transaction/BTC/broadcast",
        json={"txData": "62BD544D"},
        response={"txId": "c83f"},
        check=lambda r: isinstance(r, t.TransactionId) and r.txId == "c83f",
    ),
    # ====================================================== blockchain.wallet
    Case(
        "wallet.generate",
        "blockchain.wallet.generate",
        lambda c: c.blockchain.wallet.generate("BTC"),
        "GET",
        "/api/v1/blockchain/wallet/BTC",
        response={"mnemonic": "abandon about", "xpub": "xpub6CUG"},
        check=lambda r: isinstance(r, t.WalletHd) and r.xpub == "xpub6CUG",
        variant="hd",
    ),
    Case(
        "wallet.generate",
        "blockchain.wallet.generate",
        lambda c: c.blockchain.wallet.generate("XRP"),
        "GET",
        "/api/v1/blockchain/wallet/XRP",
        response={"address": "rXYZ", "secret": "sSecret"},
        check=lambda r: isinstance(r, t.WalletAccount) and r.secret == "sSecret",
        variant="account",
    ),
    Case(
        "wallet.generate",
        "blockchain.wallet.generate",
        lambda c: c.blockchain.wallet.generate("SOL"),
        "GET",
        "/api/v1/blockchain/wallet/SOL",
        response={"mnemonic": "m", "address": "SoL", "privateKey": "pk"},
        check=lambda r: isinstance(r, t.WalletSolana) and r.privateKey == "pk",
        variant="solana",
    ),
    Case(
        "wallet.generate",
        "blockchain.wallet.generate",
        lambda c: c.blockchain.wallet.generate("EGLD"),
        "GET",
        "/api/v1/blockchain/wallet/EGLD",
        response={"mnemonic": "m"},
        check=lambda r: isinstance(r, t.WalletEgld) and r.mnemonic == "m",
        variant="egld",
    ),
    Case(
        "address.derive",
        "blockchain.wallet.derive_address",
        lambda c: c.blockchain.wallet.derive_address("BTC", "xpub6CUG", 0),
        "GET",
        "/api/v1/blockchain/wallet/BTC/address/xpub6CUG/0",
        response={"address": "bc1qderived"},
        check=lambda r: isinstance(r, t.DerivedAddress) and r.address == "bc1qderived",
    ),
    Case(
        "privatekey.derive",
        "blockchain.wallet.derive_private_key",
        lambda c: c.blockchain.wallet.derive_private_key("BTC", mnemonic="abandon about", index=0),
        "POST",
        "/api/v1/blockchain/key/BTC/derive",
        json={"mnemonic": "abandon about", "index": 0},
        response={"key": "0xprivatekeytest123"},
        check=lambda r: isinstance(r, t.DerivedPrivateKey) and r.key == "0xprivatekeytest123",
    ),
    # =================================================== blockchain.contracts
    Case(
        "contract.token.deploy",
        "blockchain.contracts.deploy_token",
        lambda c: c.blockchain.contracts.deploy_token(
            chain="ETH",
            symbol="TKN",
            name="Token",
            supply="1000",
            address="0xrecipient",
            from_private_key="PK",
            total_cap="10000",
            digits=18,
        ),
        "POST",
        "/api/v1/blockchain/operations/contract/token/deploy",
        json={
            "chain": "ETH",
            "symbol": "TKN",
            "name": "Token",
            "totalCap": "10000",
            "supply": "1000",
            "digits": 18,
            "address": "0xrecipient",
            "fromPrivateKey": "PK",
        },
        response={"txId": "0xdeploy"},
        check=lambda r: r.txId == "0xdeploy",
    ),
    Case(
        "contract.token.mint",
        "blockchain.contracts.mint_token",
        lambda c: c.blockchain.contracts.mint_token(
            chain="BSC", contract_address="0xc", amount="5", to="0xto", from_private_key="PK"
        ),
        "POST",
        "/api/v1/blockchain/operations/contract/token/mint",
        json={"chain": "BSC", "contractAddress": "0xc", "amount": "5", "to": "0xto", "fromPrivateKey": "PK"},
        response={"txId": "0xmint"},
        check=lambda r: r.txId == "0xmint",
    ),
    Case(
        "contract.token.burn",
        "blockchain.contracts.burn_token",
        lambda c: c.blockchain.contracts.burn_token(
            chain="ETH", contract_address="0xc", amount="5", from_private_key="PK"
        ),
        "POST",
        "/api/v1/blockchain/operations/contract/token/burn",
        json={"chain": "ETH", "contractAddress": "0xc", "amount": "5", "fromPrivateKey": "PK"},
        response={"txId": "0xburn"},
        check=lambda r: r.txId == "0xburn",
    ),
    # ========================================================= blockchain.fee
    Case(
        "fee.get",
        "blockchain.fee.get_recommended_fee",
        lambda c: c.blockchain.fee.get_recommended_fee("BTC"),
        "GET",
        f"{D}/fee/BTC",
        response={
            "fast": 1.452,
            "medium": 1.193,
            "slow": 1.1,
            "block": 965924,
            "time": "2026-09-07T11:55:47.916Z",
        },
        check=lambda r: isinstance(r, t.NetworkFee) and r.fast == 1.452 and r.block == 965924,
    ),
    Case(
        "fee.gas",
        "blockchain.fee.estimate_gas",
        lambda c: c.blockchain.fee.estimate_gas("BNB", from_address="0xAb58", to="0xdEaD", amount="0.01"),
        "POST",
        f"{D}/fee/gas/BNB",
        json={"from": "0xAb58", "to": "0xdEaD", "amount": "0.01"},
        response={"gasLimit": "21000", "gasPrice": "50000000"},
        check=lambda r: isinstance(r, t.GasEstimate) and r.gasLimit == "21000",
    ),
    # ========================================================= blockchain.nft
    Case(
        "nft.collection.get",
        "blockchain.nft.list_collection",
        lambda c: c.blockchain.nft.list_collection(
            "ETH", "0xbc4c", exclude_metadata=True, page_size=10, offset=5
        ),
        "GET",
        f"{D}/nft/collection/ETH/0xbc4c",
        query={"excludeMetadata": "true", "pageSize": "10", "offset": "5"},
        response=[
            {
                "chain": "ethereum-mainnet",
                "tokenId": "1",
                "tokenAddress": "0xbc4c",
                "tokenType": "nonfungible",
                "metadata": {"name": "Bored Ape #1", "display_animation_url": None},
            }
        ],
        check=lambda r: isinstance(r[0], t.NftToken) and r[0].metadata.name == "Bored Ape #1",
    ),
    Case(
        "nft.owner.get",
        "blockchain.nft.get_owners",
        lambda c: c.blockchain.nft.get_owners("ETH", "0xbc4c", "1"),
        "GET",
        f"{D}/nft/owner/ETH/0xbc4c/1",
        response=["0x1234567890abcdef1234567890abcdef12345678"],
        check=lambda r: r == ["0x1234567890abcdef1234567890abcdef12345678"],
    ),
    # ===================================================== blockchain.storage
    Case(
        "storage.ipfs.upload",
        "blockchain.storage.upload_to_ipfs",
        lambda c: c.blockchain.storage.upload_to_ipfs(
            b"hello", filename="hello.txt", content_type="text/plain"
        ),
        "POST",
        "/api/v1/blockchain/storage/ipfs",
        status=201,
        response={"ipfsHash": "bafkreifps7p33l5cl6cbepea3nrvhs46bratq3qglfe6rdc6kusddspwfa"},
        check=lambda r: isinstance(r, t.IpfsUpload) and r.ipfsHash.startswith("bafkrei"),
    ),
]
